PSJira/Functions/Set-JiraIssue.Tests.ps1, PSJira/Functions/Set-JiraIssue.ps1
Updated ConvertTo-Json to depth 5. When updating custom multi select lists, the inner PSON object wasn't getting converted to json and causing an error. Have also updated pester test to test this.
=> Hotfix set jira issue

PSJira/Public/New-JiraIssue.ps1
Addresses #52 by making -Priority and -Description both optional.
Didn't really see a need to edit the tests file.
=> Remove mandatory flags in New-JiraIssue

PSJira/Public/Set-JiraIssueLabel.ps1
=> Forced array for label property.

PSJira/Public/New-JiraSession.ps1
=> Add test if headers contain info that captcha is required

.vscode/tasks.json, JiraPS/Public/Get-JiraVersion.ps1, JiraPS/Public/New-JiraVersion.ps1, JiraPS/Public/Remove-JiraVersion.ps1, JiraPS/Public/Set-JiraVersion.ps1, Tests/Get-JiraVersion.Tests.ps1, Tests/New-JiraVersion.Tests.ps1, Tests/Remove-JiraVersion.Tests.ps1, Tests/Set-JiraVersion.Tests.ps1, Tests/Shared.ps1
Get-JiraVersion, New-JiraVersion, Remove-JiraVersion, Set-JiraVersion
Version Functionality
closes #40
=> JiraPS Version Functionality

Tests/New-JiraVersion.Tests.ps1
Unit Test of `New-JiraVersion` was only passing because it was using a wrong variable
closes #164
=> Fix Test that was using wrong variable

JiraPS/Internal/ConvertTo-JiraVersion.ps1, JiraPS/Public/Get-JiraVersion.ps1, JiraPS/Public/New-JiraVersion.ps1, JiraPS/Public/Set-JiraVersion.ps1
Current implementation of _Version_ functions do not work with Basic Auth (`-Credential` parameter)
closes #177
=> Pass the Credential parameter down the line

JiraPS/Internal/ConvertTo-JiraVersion.ps1, JiraPS/Public/New-JiraSession.ps1, Tests/ConvertTo-JiraVersion.Tests.ps1, Tests/JiraPS.Integration.Tests.ps1
Fixes Performance issue with Get-JiraVersion (#183)
Fixes "Cannot index into a null array" when running New-JiraSession (#184) 
closes #183 , closes #184
=> Bugfix/#183 and #184

JiraPS.build.ps1
Put more logic into the generation of the exported functions and aliases
closes #186
=> Improve the update of the manifest on build

JiraPS/Public/Add-JiraIssueComment.ps1
Change the default visibility of comments to _All Users_
closes #172
=> Fix default value of Visibility of comments

JiraPS/Public/New-JiraSession.ps1
This implements a check if the hashtable contains the key we need
closes #185
=> Add a check that the header actually contains the key

JiraPS/Internal/ConvertTo-JiraUser.ps1, Tests/ConvertTo-JiraUser.Tests.ps1
Adds all possible properties of an User object.
closes #152
=> Add missing properties to User

.gitignore, CHANGELOG.md, JiraPS/Internal/ConvertTo-JiraAttachment.ps1, JiraPS/Internal/ConvertTo-JiraIssue.ps1, JiraPS/Internal/Invoke-JiraMethod.ps1, JiraPS/JiraPS.psd1, JiraPS/Public/Add-JiraIssueAttachment.ps1, JiraPS/Public/Get-JiraIssueAttachment.ps1, JiraPS/Public/Remove-JiraIssueAttachment.ps1, README.md, Tests/Add-JiraIssueAttachment.Tests.ps1, Tests/ConvertTo-JiraAttachment.Tests.ps1, Tests/ConvertTo-JiraIssue.Tests.ps1, Tests/Get-JiraIssueAttachment.Tests.ps1, Tests/Remove-JiraIssueAttachment.Tests.ps1, appveyor.yml
FEATURES:
- `Add-JiraIssueAttachment`: Add an attachment to an issue (#137, [@beaudryj][])
- `Get-JiraIssueAttachment`: Get attachments from issues (#137, [@beaudryj][])
- `Remove-JiraIssueAttachment`: Remove attachments from issues (#137, [@beaudryj][])
IMPROVEMENTS:
- `JiraPS.Issue` now has a property for Attachments `JiraPS.Attachment` (#137, [@beaudryj][])
closes #137 
closes #197
=> Release v2.4

JiraPS/Internal/Test-Captcha.ps1, JiraPS/Public/New-JiraSession.ps1, Tests/Add-JiraIssueAttachment.Tests.ps1, Tests/Get-JiraVersion.Tests.ps1, Tests/New-JiraVersion.Tests.ps1, Tests/Remove-JiraIssueAttachment.Tests.ps1, Tests/Remove-JiraVersion.Tests.ps1, Tests/Set-JiraVersion.Tests.ps1, Tests/Shared.ps1
* Extract captcha test
* fix empty headers (#206)
closes #206
=> Extract captcha test and fix empty headers #206

JiraPS/Public/Get-JiraIssueCreateMetadata.ps1
Fix REST API call to include the expands we need
closes #222
=> Fixed missing expands of REST resource

JiraPS/Public/Get-JiraField.ps1, JiraPS/Public/New-JiraIssue.ps1
Fixes the bad `Body` in `New-JiraIssue`
closes #224
=> Fixed how the Body of `New-JiraIssue` is created

docs/en-US/index.md
Added blank pages to the documentation to avoid 404
=> Added blank index pages

JiraPS.build.ps1, JiraPS/Public/Get-JiraUser.ps1, Tests/Get-JiraUser.Tests.ps1, docs/en-US/commands/Get-JiraUser.md
Allow for querying the user that is running the command.
closes #231
=> Get current user

JiraPS/Public/Invoke-JiraIssueTransition.ps1, Tests/Invoke-JiraIssueTransition.Tests.ps1, docs/en-US/commands/Invoke-JiraIssueTransition.md
Return the updated issue after invoking a transition when `-Passthru` is provided
closes #204
=> Added a Passthru parameter to Invoke-JiraIssueTransition

docs/en-US/about_JiraPS_UpdatingIssues.md
Removed BOM from UTF-8 encoding of file.
=> Updated file encoding

JiraPS/Public/Set-JiraIssueLabel.ps1
* removing labels was using a wrong variable
* adding multiple labels at once was bugged
=> Fixed the process to add and remove labels from issue

README.md
Fixes SVG icon for AppVeyor status
=> Fix icon for CI

JiraPS.build.ps1
Reduce the amount of data in the CI's console by only showing Pester tests that fail
=> Reduced the console output in the CI

JiraPS.build.ps1
Update the submodule in the homepage repository
=> Fixed deployment of hompage update

JiraPS/Public/Get-JiraUser.ps1, Tests/Get-JiraUser.Tests.ps1, docs/en-US/commands/Get-JiraUser.md
Add a parameter to determine how many results `Get-JiraUser` can return and how many to skip
resolves #246
=> Added parameter to influence max# of users to search

JiraPS.build.ps1, JiraPS/Public/Get-JiraRemoteLink.ps1, Tests/Get-JiraRemoteLink.Tests.ps1, Tests/JiraPS.Integration.Tests.ps1, appveyor.yml
`Get-JiraRemoteLink` was using the wrong function for converting the response to object
=> Fix Resolving of remote link object

JiraPS/Public/New-JiraFilter.ps1
This change fixes the case of the properties in the post request for creating a new filter
=> Fixed the payload for creating a new filter

JiraPS/Private/Convert-Result.ps1, JiraPS/Private/Expand-Result.ps1, JiraPS/Public/Invoke-JiraMethod.ps1, Tests/Invoke-JiraMethod.Tests.ps1
Fixed loop over paged results when the last page contains only 1 entry
closes #307
=> Fixed pagination with 1 result on page

JiraPS/Public/Set-JiraIssue.ps1, Tests/Set-JiraIssue.Tests.ps1, docs/en-US/commands/Set-JiraIssue.md
Fixed how the assignee is removed from an issue
Also added "default"
=> Fixed setting the assignee to null

JiraPS/Public/Get-JiraUser.ps1, Tests/Functions/Get-JiraUser.Unit.Tests.ps1
Added the groups property for the current user (`Get-JiraUser`)
closes #319
=> Added group membership when querying the current user

JiraPS/Public/Get-JiraComponent.ps1
Logic for retrieving components from project now works fine for Project objects over the pipeline
=> Fixed logic of how to retrieve components from project

Tests/Help.Tests.ps1
Added Pester Test to test that all the public functions docs contains .SYNTAX 
fixed issue #278
=> fixing issue-278 'Add test for syntax in documentation'

JiraPS/Private/Resolve-JiraIssueObject.ps1, JiraPS/Private/Resolve-JiraUser.ps1, JiraPS/Public/Add-JiraGroupMember.ps1, JiraPS/Public/Get-JiraUser.ps1, JiraPS/Public/Invoke-JiraIssueTransition.ps1, JiraPS/Public/Remove-JiraGroupMember.ps1, JiraPS/Public/Remove-JiraUser.ps1, JiraPS/Public/Set-JiraIssue.ps1, JiraPS/Public/Set-JiraUser.ps1
Added better handling for resolving the user from an object or a string
closes #367
=> Fix #367: Incorrect Resolving Of User

JiraPS/Public/Get-JiraConfigServer.ps1, Tests/JiraPS.Tests.ps1
Added check for trailing `/` to be removed from `JiraServerUrl`
closes #372
=> Added check for trailing `/` to be removed from `JiraServerUrl`

docs/en-US/about_JiraPS_Authentication.md
Documentation on the usage of PAT for authenticating with Jira Cloud APIs is not clear about what value to use as value for `user` in the credentials.
closes #353
=> Improved documentation for PAT

JiraPS/Public/New-JiraSession.ps1, Tests/Functions/New-JiraSession.Unit.Tests.ps1
Atlassian changed the route which this module used to create a new session with `New-JiraSession`.
Atlassian announced it in this post: https://developer.atlassian.com/cloud/jira/platform/change-notice-get-my-permissions-requires-permissions-query-parameter/
closes #390
=> Fixed route for creating session

CHANGELOG.md, JiraPS.build.ps1, JiraPS/JiraPS.psd1, Tools/BuildTools.psm1
- Add support for activation/deactivation of accounts via `Set-JiraUser` (#385, [@johnheusinger])
- Removed progress bar from `Invoke-WebRequest` for better performance (#380, [@sgtwilko])
=> Release of 2.13

Tests/Functions/Get-JiraIssue.Unit.Tests.ps1
Describe block title should be "Get-JiraIssue"
fixed simple typo
typo
=> Describe block title typo

JiraPS/Public/New-JiraIssue.ps1
New changes in the JIRA API are breaking a lot of functionality. This is fixing one of them
=> Remove the setting of the reporter for new issue in next-gen projects

JiraPS/Public/Format-Jira.ps1
Fix multiplication of properties across all objects in InputObject when not using pipeline
closes #437
=> Fix cross-multiplication of properties in Format-Jira

.github/workflows/build_and_test.yml
Add a `push` trigger to the `build_and_test` workflow
This will provide an additional confirmation that all checks are passing after merging a PR to the master branch.
It should also fix the 'build status' badge in the readme (currently showing 'no status')
=> Add 'push' trigger to build_and_test workflow

.github/dependabot.yml
Use github's dependabot for keeping up to date with actions in our workflows
=> Added dependabot to keep github actions up-to-date
