- PSJira/Functions/New-JiraIssue.ps1
This is needed in order to support sub-task issues, and addresses #29.
> Adding optional parameter to specify a parent key

- PSJira/Internal/Invoke-JiraMethod.ps1
- PSJira/Public/New-JiraSession.ps1
Take over global PSDefaultParameterValues from global scope to local, so that nested function will use the same PSDefaultParameterValues
closes #97
> Take over global PSDefaultParameterValues

- PSJira/Internal/Invoke-JiraMethod.ps1
- PSJira/Public/New-JiraSession.ps1
- Tests/Invoke-JiraMethod.Tests.ps1
Send ContentType as Property of the `Invoke-WebRequest` command instead of inside the Header hashtable
PR #19 described an error
> The 'Content-Type' header must be modified using the appropriate property or method.
because `Invoke-WebRequest` was sending the `content type` in the header of the request.
PR #19  contained the changes necessary, but was never merged back to `dev`/`master`.
Credit goes to @lukhase
closes #19
> Send ContentType as Parameter instead of in the Header

- JiraPS/Public/Set-JiraIssue.ps1
- Tests/Set-JiraIssue.Tests.ps1
- docs/updating_issues.rst
This PR introduces the `-AddComment` parameter for [`Set-JiraIssue`](https://github.com/AtlassianPS/JiraPS/blob/master/JiraPS/Public/Set-JiraIssue.ps1) which allows adding comments to changes.
closes #167
> Add -AddComment to Set-JiraIssue

- JiraPS/Internal/Invoke-JiraMethod.ps1
Invoke-JiraMethod was trying to invoke `Get-Member` on `$result`.
For when `$result` is empty, the module was writing a non-API related error in the error stream.
Now `$result` is check before using it.
closes #209
> Fix #209 - Indexing into Null Object

- JiraPS/Internal/Invoke-JiraMethod.ps1
Our implementation of Jira requires the setting of the Resolution during the transition.  For example when an issue is marked as "Resolved",  you can choose a resolution like "Duplicate", "Fixed", "Later"....
This change is needed in our implementation of Jira to allow the setting of the resolution during Transitiontime.
--- the way i implemented it, could cause issues in a different Jira configuration.
I added a new parameter to this module called Resolution
I updated the $props variable on line 96 to send the proper json to update the resolution field.
[Invoke-JiraIssueTransition.zip](https://github.com/AtlassianPS/JiraPS/files/1817874/Invoke-JiraIssueTransition.zip)
> Transition with Resolution

- JiraPS/Public/New-JiraIssue.ps1
Rewriting of the `New-JiraIssue` introduced an error in how the labels array is constructed.
This change fixes the problem.
closes #226
> Fixed an overlook in how the array of labels is constructed

- JiraPS/Public/Get-JiraIssue.ps1
- docs/en-US/about_JiraPS.md
In the documentation of the module, an example was using the parameter `-Issue` for `Get-JiraIssue`.
This parameter has never existed and was thus a bug in the documentation.
This change fixes the documentation and introduces an alias for the parameter `-Key` named `-Issue`.
closes #262
> Added parameter alias

- JiraPS/Public/Get-JiraIssue.ps1
- docs/en-US/about_JiraPS.md
This is the same as #267, which was merged into the wrong base.
Changed the way Credentials are passed to the functions.
These changes are 100% backwards compatible but add new functionality:
```powershell
Get-JiraIssue -Credential "lipkau"
```
`lipkau` is a string. This was not possible before this change.
Now, `-Credential` will call `Get-Credential -UserName $_` when a string is provided.
Improve usability
> Enhance credential handling (again)

- .editorconfig
- .gitattributes
- _posts/2017-06-24-JiraPS-v2.0.md
- _posts/2017-06-25-JiraPS-v2.1.md
- _posts/2017-08-05-JiraPS-v2.2.md
- _posts/2017-10-07-JiraPS-v2.3.md
- _posts/2017-12-05-JiraPS-v2.4.md
- _posts/2018-03-22-JiraPS-v2.5.md
- _posts/2018-05-04-JiraPS-v2.6.md
- _posts/2018-05-13-JiraPS-v2.7.md
by maintaining the homepage posts in this repo,
it is now possible to create a new post announcing
a new version of JiraPS and the CI will publish them.
This automates the process of having to publish the article shortly after the CI finished successfully.
> automated publishing of posts

- JiraPS/JiraPS.psm1
- JiraPS/Public/Invoke-JiraMethod.ps1
This PR modifies `Invoke-JiraMethod` to improve error-parsing under certain conditions. 
More specifically, the following changes have been made:
* Appropriately parse errors in the event the Jira API returns an error in a manner that populates the `ErrorDetails` field on the associated exception. (see #276)
* Handle API responses that are neither valid JSON nor HTML.
* Catch errors that only include the `errorMessages` property versus the `errors` property.
If Jira (or the web server/proxy used to access it) is using Chunked transfer encoding, for instance, this field may not be populated (see [this PowerShell UserVoice post](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/17142518--errordetails-is-null-when-invoke-webrequest-or)).
This PR resolves #276.
> Improve error-handler to accommodate for ErrorDetails and non-JSON/HTML responses

- JiraPS/Public/Remove-JiraFilter.ps1
- Tests/Remove-JiraFilter.Tests.ps1
- docs/en-US/commands/Remove-JiraFilter.md
by adding the `-Id` parameter, Remove-JiraFilter is able to take an Integer over the pipeline.
This enables the used to get the data from a file (or similar)
> Added `-Id` parameter to Remove-JiraFilter

- JiraPS/Public/Remove-JiraGroupMember.ps1
- Tests/Remove-JiraGroupMember.Tests.ps1
When `Remove-JiraGroupMember` uses a `[String]` for `-User`, `Get-JiraUser` does not resolve properly resolve the input.
This is fixed by using `-UserName` instead of `-InputObject` on `Get-JiraUser`
closes #299
> Fixed the way a string of an user is resolved

- JiraPS/Private/Resolve-ErrorWebResponse.ps1
- JiraPS/Public/Get-JiraIssueWatcher.ps1
- JiraPS/Public/Get-JiraVersion.ps1
- JiraPS/Public/Invoke-JiraMethod.ps1
- JiraPS/Public/New-JiraIssue.ps1
- JiraPS/Public/Remove-JiraGroupMember.ps1
* error objects are now converted to a string and displayed properly
* Functions which use a property of the response will ignore the result if empty
closes #302
> Fixed handling of server responses with an error

- JiraPS/Public/New-JiraIssue.ps1
- Tests/New-JiraIssue.Tests.ps1
- docs/en-US/commands/New-JiraIssue.md
The here was due to how PowerShell handles input via the pipeline, see an in depth explanation with examples here: https://learn-powershell.net/2013/05/07/tips-on-implementing-pipeline-support/.
The function will be unable to use $Profile in the begin block, so i moved that code into the Process block. This is necessary so that multiple new issues can be passed in and processed one after the other.
This resolves https://github.com/AtlassianPS/JiraPS/issues/229 and allows a user to fill an excel sheet or other object with new issues and pipe them into new issue.
closes #229
> Fix issue 229 - New-JiraIssue should take params from pipeline.

- docs/en-US/about_JiraPS_Authentication.md
Updated the documentation on how to authenticate to include instructions on how to use an API Token.
This is currently the only way to authenticate if the user has two-step authorization
closes #313
> Added documentation for authenticating with PAT

- JiraPS/Public/Get-JiraIssueAttachment.ps1
- JiraPS/Public/Get-JiraIssueAttachmentFile.ps1
- Tests/Functions/Get-JiraIssueAttachmentFile.Unit.Tests.ps1
- docs/en-US/commands/Get-JiraIssueAttachmentFile.md
Added function for persisting an attachment of an issue to the disk
closes #318
> Download of Attachments

- JiraPS/Public/Add-JiraIssueWorklog.ps1
- Tests/Functions/Add-JiraIssueWorklog.Unit.Tests.ps1
Fixed the string representation of DateTime for DateStarted.
The API requires the timezone, which is not always available in `[DateTime]`.
Eg: `Get-Date -Date "01.01.2000"`
closes #324
> Fixed DateTime format

- CHANGELOG.md
- JiraPS/Public/Get-JiraUser.ps1
- JiraPS/Public/Set-JiraIssue.ps1
- Tests/Functions/Get-JiraUser.Unit.Tests.ps1
- docs/en-US/commands/Get-JiraUser.md
Adds `-Exact` parameter to the `Get-JiraUser` which internally switches from using search to get user. 
It is then used in the `Set-JiraIssue` when the `-Assignee` is set.
closes #320 
closes #49
is continued by #306
Assigning users failing when `Get-JiraUser` for a specific username returns more than one user
> fixes 320 - assignment when similar users exist

- JiraPS/Private/ConvertTo-JiraProject.ps1
- JiraPS/Public/Get-JiraIssueCreateMetadata.ps1
- JiraPS/Public/New-JiraIssue.ps1
- Tests/Functions/Get-JiraIssueCreateMetadata.Unit.Tests.ps1
- Tests/Functions/New-JiraIssue.Unit.Tests.ps1
Modified ConvertTo-JiraProject to store the 'style' value returned from project REST API so a given project can be differentiated between next-gen or classic.
Modified New-JiraIssue (and similarly to Get-JiraIssueCreateMetadata) to avoid use of Get-JiraIssueType - all the data that required this cmdlet to be called is already stored in $projectObj. Additionally, Get-JiraIssueType does not support mixed environments with classic and next-gen projects. The original errors we got were a result of Get-JiraIssueType returning multiple IDs for a given Issue Type name.
New-JiraIssue also had an issue with the "reporter" field being unset on a next-gen project. Classic projects seems to automatically set the reporter field to the current user if not set, but next-gen projects do not seem to …
> Fix usage of New-JiraIssue in Jira Environment with mixed classic and "next gen" projects

- JiraPS/Public/Get-JiraIssueAttachmentFile.ps1
The attachment objects have a `MimeType` property.  This should be used to set the `Accept` header in the request to download the actual attachment; however the existing code refers to (non-existing) `MediaType` property on the Powershell object, thereby setting the Accept header value to null. 
A partial fix for apparently "successful" download of file attachments. Without this change the pipeline output is `True` for each attachment downloaded, but the attachment did not download.  This PR doesn't change the fautly error handling, but implements a trivial underlying fix to constructing the request to fetch the download.
I believe that the error handling code needs to be fixed too, but I've not had a chance to do that.
> Get-JiraIssueAttachmentFile: Set Accept header based on Mime time of attachment

- JiraPS/Public/Set-JiraIssue.ps1
`false` in the get parameter `notifyUsers=false` must be lowercase
closes #338
> Fix incorrect handling of skip notifications

- JiraPS/Public/Invoke-JiraIssueTransition.ps1
If JIRA has usernames such as "jsmith", "jsmithy", "jsmith1", "jsmithson" and you are trying to assign the ticket to "jsmith" it will fail because the assignee field needs a single user object to get a single string from but Get-JiraUser is returning an array of user objects.
By adding the Exact flag to the Get-JiraUser function within the Invoke-JiraIssueTransition this issue is resolved as only one user object is returned.
If JIRA has usernames such as "jsmith", "jsmithy", "jsmith1", "jsmithson" and you are trying to assign the ticket to "jsmith" it will fail because the assignee field needs a single user object to get a single string from but Get-JiraUser is returning an array of user objects.
closes #349
> Added -Exact flag to Get-JiraUser

- JiraPS/Public/Set-JiraIssueLabel.ps1
The array of labels was created with `null` as the first entry,
if the issue didn't have labels before
> Fixed method for adding labels to issue

- JiraPS/Public/Get-JiraUser.ps1
- JiraPS/Public/Move-JiraVersion.ps1
- Tests/Functions/Move-JiraVersion.Unit.Tests.ps1
- docs/en-US/commands/Get-JiraUser.md
- docs/en-US/commands/Get-JiraVersion.md
- docs/en-US/commands/Move-JiraVersion.md
- docs/en-US/commands/New-JiraVersion.md
- docs/en-US/commands/Remove-JiraVersion.md
- docs/en-US/commands/Set-JiraVersion.md
Add Move-JiraVersion method
/version/{id}/move was missing from current functionality
> Add Move-JiraVersion method

- JiraPS/Public/Find-JiraFilter.ps1
- Tests/Functions/Find-JiraFilter.Unit.Tests.ps1
- docs/en-US/commands/Find-JiraFilter.md
Adds a Find-JiraFilter function to facilitate finding filters by name (among other things) when the Id is not known.  The relevant rest api endpoint is [/rest/api/3/filter/search](https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-filter-search-get).
Get-JiraFilter lacks the ability to retrieve a filter by name, and the performance of its' -Favorite switch is inadequate for large result sets.
> Find-JiraFilter

- JiraPS/JiraPS.psm1
- JiraPS/Public/Get-JiraConfigServer.ps1
- JiraPS/Public/Set-JiraConfigServer.ps1
- Tests/Functions/Get-JiraConfigServer.Unit.Tests.ps1
- Tests/Functions/Set-JiraConfigServer.Unit.Tests.ps1
- Tests/JiraPS.Tests.ps1
- docs/en-US/commands/Get-JiraConfigServer.md
- docs/en-US/commands/Set-JiraConfigServer.md
Have `Set-JiraConfigServer` store the server in the module's session instead of in a file.
Several issues were raised asking for help because the `config.xml` could not be written (or changed)
> Changed ConfigServer to be in module's scope

- JiraPS/Public/New-JiraUser.ps1
Changed 'notify' to 'notification' in the request body to align with API documentation
Closes issue #382
> Fix email notification not sending

- JiraPS/Public/Set-JiraUser.ps1
- docs/en-US/commands/Set-JiraUser.md
Add '-Active' parameter to Set-JiraUser, changing status to active or inactive. If unspecified, no change is performed.
Closes #376
> Add support for activation/deactivation of accounts via Set-JiraUser

- JiraPS/Public/Invoke-JiraMethod.ps1
Normal ProgressPreference really slows down invoke-webrequest as it tries to update the screen for bytes received.
By setting ProgressPreference to silentlyContinue it doesn't try to update the screen and speeds up the downloads.
See https://stackoverflow.com/a/43477248/2641196
This change make a reasonable difference to the speed of accessing Jira systems with large numbers of fields, or for methods that make large number of calls.
This improves, but does not entirely resolve #362
> Speedup Invoke-WebRequests by disabling progress indicator.

- JiraPS/Public/Add-JiraGroupMember.ps1
In Add-JiraGroupMember.Unit.Tests.ps1, these two tests require the `Add-JiraGroupMember` to handle the supplied ErrorAction parameter:
* "Tests to see if a provided user is currently a member of the provided JIRA group before attempting to add them"
* "Gracefully handles cases where a provided user is already in the provided group"
I switched the `Write-Error` to `WriteError` and adjusted the splat parameter to supply the necessary parameters
This change is necessary to enable the tests to pass.
closes #425
> Modify Add-JiraGroupMember so that it honors ErrorAction

- .editorconfig
- .github/CODEOWNERS
- .github/workflows/build_and_test.yml
- .github/workflows/pr_review.yml
Small improvements to CI pipeline:
* added PS module caching
* added upload of test results in ci
* added yaml file settings
> Feature: caching improvements to ci

- JiraPS/Private/ConvertTo-JiraCreateMetaField.ps1
- JiraPS/Public/Get-JiraIssueCreateMetadata.ps1
- Tests/Functions/ConvertTo-JiraCreateMetaField.Unit.Tests.ps1
The createmeta API call has changed. As per: https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html
The path for the API call and the data returned have changed format. This causes the New-JiraIssue commandlet to fail. This change addresses both the change in URI and the change in format.
This change addresses an API issue with the createmeta API call.
https://github.com/AtlassianPS/JiraPS/issues/473
> Createmeta update

- JiraPS/JiraPS.psm1
This PR allows the .NET runtime to create the ApplicationData folder for us, even if it doesn't exist yet.
This occurs frequently in serverless environments, where variables like `XDG_CONFIG_DIR` may be set to non-standard values.
Not providing this flag to `GetFolderPath` causes it to return an empty string if the folder doesn't exist.
Fixes #512.
> Enable creation of ApplicationData folder if it doesn't exist yet

- JiraPS/Public/New-JiraIssue.ps1
- JiraPS/Public/Set-JiraIssue.ps1
- Tests/Functions/New-JiraIssue.Unit.Tests.ps1
- Tests/Functions/Set-JiraIssue.Unit.Tests.ps1
This PR adjusts the functionality of `New-JiraIssue` and `Set-JiraIssue` to only call `Get-JiraField` once (if `-Fields` is set) instead of once per entry in the `-Fields` hashtable.
Additionally, both cmdlets will resolve numerical IDs for custom fields if users specify fields in that way (i.e. `-Fields @{12345 = $foo}` is equivalent to `-Fields @{customfield_12345 = $foo}`)
`Get-JiraField` takes a `-Name` parameter, however the underlying API call is not filtered by name. This means that every field in the instance (visible to the current user) is retrieved for each key in `-Fields`. This means network traffic/CPU usage/time spent scales quadratically in practice (linear to the number of CFs in the API call and the number of CFs in the instance).
By moving `Get-JiraField` out of this …
> Improve performance of `New-`/`Set-JiraIssue` on instances with large quantities of fields

- JiraPS/Public/New-JiraIssue.ps1
- JiraPS/Public/Set-JiraIssue.ps1
- Tests/Functions/New-JiraIssue.Unit.Tests.ps1
- docs/en-US/commands/New-JiraIssue.md
This PR aligns the naming convention for label parameters between `New-JiraIssue` and `Set-JiraIssue`.
Resolves #521.
`New-JiraIssue` takes `-Labels`, whereas `Set-JiraIssue` takes `-Label`. This PR updates both to be `-Label` with `-Labels` as an alias for backwards compatibility.
> Unify Label parameter names to singular form in `New-`/`Set-JiraIssue`
